<?php

/*
| Kode bank BI (beneficiaryBankCode) dan kode SWIFT untuk Espay Disbursement (BI-FAST).
| Sumber: panduan-espey/Bank_and_Swift_Code.xlsx (docs.espay.id > Disbursement > Kode Bank dan Swift Kode, 138 baris).
| Kode bank yang punya unit usaha syariah memakai SWIFT unit konvensional.
*/

return [
    '001' => ['name' => 'BANK INDONESIA', 'swift' => 'INDOIDJA'],
    '002' => ['name' => 'PT. BANK RAKYAT INDONESIA (PERSERO)', 'swift' => 'BRINIDJA'],
    '008' => ['name' => 'PT. BANK MANDIRI (PERSERO) TBK', 'swift' => 'BMRIIDJA'],
    '009' => ['name' => 'PT. BANK NEGARA INDONESIA (PERSERO)', 'swift' => 'BNINIDJA'],
    '011' => ['name' => 'PT. BANK DANAMON INDONESIA Tbk.', 'swift' => 'BDINIDJA'],
    '013' => ['name' => 'PT. BANK PERMATA,TBK', 'swift' => 'BBBAIDJA'],
    '014' => ['name' => 'PT. BANK CENTRAL ASIA Tbk.', 'swift' => 'CENAIDJA'],
    '016' => ['name' => 'PT. BANK MAYBANK INDONESIA Tbk.', 'swift' => 'IBBKIDJA'],
    '019' => ['name' => 'PT. PANIN BANK Tbk.', 'swift' => 'PINBIDJA'],
    '022' => ['name' => 'PT. BANK CIMB NIAGA TBK', 'swift' => 'BNIAIDJA'],
    '023' => ['name' => 'PT. BANK UOB INDONESIA', 'swift' => 'BBIJIDJA'],
    '028' => ['name' => 'PT. BANK OCBC NISP, Tbk.', 'swift' => 'NISPIDJA'],
    '031' => ['name' => 'CITIBANK, NA', 'swift' => 'CITIIDJX'],
    '032' => ['name' => 'KC JPMORGAN CHASE BANK, N.A', 'swift' => 'CHASIDJX'],
    '033' => ['name' => 'BANK OF AMERICA NA', 'swift' => 'BOFAID2X'],
    '036' => ['name' => 'PT. BANK WINDU KENTJANA INTERNASIONAL, TBK', 'swift' => 'MCORIDJA'],
    '037' => ['name' => 'PT. BANK ARTHA GRAHA INTERNASIONAL, TBK', 'swift' => 'ARTGIDJA'],
    '040' => ['name' => 'BANGKOK BANK PUBLIC CO.LTD', 'swift' => 'BKKBIDJA'],
    '041' => ['name' => 'THE HONGKONG & SHANGHAI BANKING CORP. LTD.', 'swift' => 'HSBCIDJA'],
    '042' => ['name' => 'THE BANK OF TOKYO MITSUBISHI UFJ LTD.', 'swift' => 'BOTKIDJX'],
    '045' => ['name' => 'PT. BANK SUMITOMO MITSUI INDONESIA', 'swift' => 'SUNIIDJA'],
    '046' => ['name' => 'PT. BANK DBS INDONESIA', 'swift' => 'DBSBIDJA'],
    '047' => ['name' => 'PT. BANK RESONA PERDANIA', 'swift' => 'BPIAIDJA'],
    '048' => ['name' => 'PT. BANK MIZUHO INDONESIA', 'swift' => 'MHCCIDJA'],
    '050' => ['name' => 'STANDARD CHARTERED BANK', 'swift' => 'SCBLIDJX'],
    '052' => ['name' => 'THE ROYAL BANK OF SCOTLAND N.V.', 'swift' => 'ABNAIDJA'],
    '054' => ['name' => 'PT BANK CAPITAL INDONESIA', 'swift' => 'BCIAIDJA'],
    '057' => ['name' => 'PT. BANK BNP PARIBAS INDONESIA', 'swift' => 'BNPAIDJA'],
    '061' => ['name' => 'PT. BANK ANZ INDONESIA', 'swift' => 'ANZBIDJX'],
    '067' => ['name' => 'DEUTSCHE BANK AG.', 'swift' => 'DEUTIDJA'],
    '069' => ['name' => 'BANK OF CHINA', 'swift' => 'BKCHIDJA'],
    '076' => ['name' => 'PT. BANK BUMI ARTA', 'swift' => 'BBAIIDJA'],
    '087' => ['name' => 'PT. BANK EKONOMI RAHARJA', 'swift' => 'EKONIDJA'],
    '088' => ['name' => 'PT. BANK ANTAR DAERAH', 'swift' => 'ANTDIDJD'],
    '089' => ['name' => 'PT. BANK RABOBANK INTERNATIONAL INDONESIA', 'swift' => 'RABOIDJA'],
    '095' => ['name' => 'PT. BANK JTRUST INDONESIA, TBK', 'swift' => 'CICTIDJA'],
    '097' => ['name' => 'PT. BANK MAYAPADA Tbk.', 'swift' => 'MAYAIDJA'],
    '110' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH JABAR DAN BANTEN', 'swift' => 'PDJBIDJA'],
    '111' => ['name' => 'PT. BANK DKI', 'swift' => 'BDKIIDJ1'],
    '112' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH DIY', 'swift' => 'PDYKIDJ1'],
    '113' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH JAWA TENGAH', 'swift' => 'PDJGIDJ1'],
    '114' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH JATIM', 'swift' => 'PDJTIDJ1'],
    '115' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH JAMBI', 'swift' => 'PDJMIDJ1'],
    '116' => ['name' => 'PT. BANK ACEH', 'swift' => 'PDACIDJ1'],
    '117' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH SUMUT', 'swift' => 'PDSUIDJ1'],
    '118' => ['name' => 'PT. BANK NAGARI', 'swift' => 'PDSBIDJ'],
    '119' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH RIAU KEPRI', 'swift' => 'PDRIIDJA'],
    '120' => ['name' => 'PT. BPD SUMSEL DAN BABEL', 'swift' => 'BSSPIDSP'],
    '121' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH LAMPUNG', 'swift' => 'PDLPIDJ1'],
    '122' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH KALSEL', 'swift' => 'PDKSIDJ1'],
    '123' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH KALBAR', 'swift' => 'PDKBIDJ1'],
    '124' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH KALTIM', 'swift' => 'PDKTIDJ1'],
    '125' => ['name' => 'PT. BPD KALIMANTAN TENGAH', 'swift' => 'PDKGIDJ1'],
    '126' => ['name' => 'PT. BANK SULSELBAR', 'swift' => 'PDWSIDJ1'],
    '127' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH SULUT', 'swift' => 'PDWUIDJ1'],
    '128' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH NTB', 'swift' => 'PDNBIDJ1'],
    '129' => ['name' => 'PT. BANK PEMBANGUNAN DAERAH BALI', 'swift' => 'ABALIDBS'],
    '130' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH NTT', 'swift' => 'PDNTIDJ1'],
    '131' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH MALUKU', 'swift' => 'PDMLIDJ1'],
    '132' => ['name' => 'PT.BANK PEMBANGUNAN DAERAH PAPUA', 'swift' => 'PDIJIDJ1'],
    '133' => ['name' => 'PT. BPD BENGKULU', 'swift' => 'PDBKIDJ1'],
    '134' => ['name' => 'PT. BPD SULAWESI TENGAH', 'swift' => 'PDWGIDJ1'],
    '135' => ['name' => 'PT. BPD SULAWESI TENGGARA', 'swift' => 'PDWRIDJ1'],
    '145' => ['name' => 'PT. BANK NUSANTARA PARAHYANGAN', 'swift' => 'NUPAIDJ6'],
    '146' => ['name' => 'PT. BANK OF INDIA INDONESIA, TBK', 'swift' => 'SWBAIDJ1'],
    '147' => ['name' => 'PT. BANK MUAMALAT INDONESIA', 'swift' => 'MUABIDJA'],
    '151' => ['name' => 'PT. BANK MESTIKA DHARMA', 'swift' => 'MEDHIDS1'],
    '152' => ['name' => 'PT. BANK SHINHAN INDONESIA', 'swift' => 'MEEKIDJ1'],
    '153' => ['name' => 'PT. BANK SINARMAS', 'swift' => 'SBJKIDJA'],
    '157' => ['name' => 'PT. BANK MASPION', 'swift' => 'MASDIDJ1'],
    '161' => ['name' => 'PT. BANK GANESHA', 'swift' => 'GNESIDJA'],
    '164' => ['name' => 'PT. BANK ICBC INDONESIA', 'swift' => 'ICBKIDJA'],
    '167' => ['name' => 'PT. BANK QNB INDONESIA,TBK', 'swift' => 'AWANIDJA'],
    '200' => ['name' => 'PT. BANK TABUNGAN NEGARA (PERSERO)', 'swift' => 'BTANIDJA'],
    '212' => ['name' => 'PT. BANK WOORI SAUDARA INDONESIA 1906,TBK', 'swift' => 'BSDRIDJA'],
    '213' => ['name' => 'PT. BANK BTPN', 'swift' => 'TAPEIDJ1'],
    '405' => ['name' => 'PT. BANK VICTORIA SYARIAH', 'swift' => 'SWAGIDJ1'],
    '422' => ['name' => 'PT. BANK SYARIAH BRI', 'swift' => 'DJARIDJ1'],
    '425' => ['name' => 'PT. BANK JABAR BANTEN SYARIAH', 'swift' => 'SYJBIDJ1'],
    '426' => ['name' => 'PT. BANK MEGA Tbk.', 'swift' => 'MEGAIDJA'],
    '427' => ['name' => 'PT BANK BNI SYARIAH', 'swift' => 'SYNIIDJ1'],
    '441' => ['name' => 'PT. BANK BUKOPIN Tbk.', 'swift' => 'BBUKIDJA'],
    '451' => ['name' => 'PT. BANK SYARIAH MANDIRI Tbk.', 'swift' => 'BSMDIDJA'],
    '459' => ['name' => 'PT. BANK BISNIS INTERNASIONAL', 'swift' => 'BUSTIDJ1'],
    '466' => ['name' => 'PT. BANK ANDARA', 'swift' => 'RIPAIDJ1'],
    '472' => ['name' => 'PT. BANK JASA JAKARTA', 'swift' => 'JSABIDJ1'],
    '484' => ['name' => 'PT. BANK KEB HANA INDONESIA', 'swift' => 'HNBNIDJA'],
    '485' => ['name' => 'PT. BANK MNC INTERNASIONAL, TBK', 'swift' => 'BUMIIDJA'],
    '490' => ['name' => 'PT. BANK YUDHA BHAKTI', 'swift' => 'YUDBIDJ1'],
    '491' => ['name' => 'PT. BANK MITRANIAGA', 'swift' => 'MGABIDJ1'],
    '494' => ['name' => 'PT. BANK RAKYAT INDONESIA AGRONIAGA, TBK', 'swift' => 'AGTBIDJA'],
    '498' => ['name' => 'PT. BANK SBI INDONESIA', 'swift' => 'IDMOIDJ1'],
    '501' => ['name' => 'PT. BANK ROYAL INDONESIA', 'swift' => 'ROYBIDJ1'],
    '503' => ['name' => 'PT. BANK NATIONALNOBU', 'swift' => 'LFIBIDJ1'],
    '506' => ['name' => 'PT. BANK MEGA SYARIAH', 'swift' => 'BUTGIDJ1'],
    '513' => ['name' => 'PT. BANK INA PERDANA', 'swift' => 'INPBIDJ1'],
    '517' => ['name' => 'PT. BANK PANIN SYARIAH', 'swift' => 'ARFAIDJ1'],
    '520' => ['name' => 'PT. PRIMA MASTER BANK', 'swift' => 'PMASIDJ1'],
    '521' => ['name' => 'PT. BANK SYARIAH BUKOPIN', 'swift' => 'SDOBIDJ1'],
    '523' => ['name' => 'PT. BANK SAHABAT SAMPOERNA', 'swift' => 'BDIPIDJ1'],
    '526' => ['name' => 'PT. BANK DINAR INDONESIA', 'swift' => 'LMANIDJ1'],
    '531' => ['name' => 'PT. BANK AMAR INDONESIA', 'swift' => 'LOMAIDJ1'],
    '535' => ['name' => 'PT. BANK KESEJAHTERAAN EKONOMI', 'swift' => 'KSEBIDJ1'],
    '536' => ['name' => 'PT. BANK BCA SYARIAH', 'swift' => 'SYCAIDJ1'],
    '542' => ['name' => 'PT. BANK ARTOS INDONESIA', 'swift' => 'ATOSIDJ1'],
    '547' => ['name' => 'PT. BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH', 'swift' => 'PUBAIDJ1'],
    '548' => ['name' => 'PT. BANK MULTI ARTA SENTOSA', 'swift' => 'MASBIDJ1'],
    '553' => ['name' => 'PT. BANK MAYORA', 'swift' => 'MAYOIDJA'],
    '555' => ['name' => 'BANK INDEX SELINDO', 'swift' => 'BIDXIDJA'],
    '558' => ['name' => 'PT. BANK PUNDI INDONESIA, TBK', 'swift' => 'EKSTIDJ1'],
    '559' => ['name' => 'PT. CENTRATAMA NASIONAL BANK', 'swift' => 'CNBAIDJ1'],
    '562' => ['name' => 'PT. BANK FAMA INTERNATIONAL', 'swift' => 'FAMAIDJ1'],
    '564' => ['name' => 'PT. BANK MANDIRI TASPEN POS', 'swift' => 'SIHBIDJ1'],
    '566' => ['name' => 'PT. BANK VICTORIA INTERNATIONAL', 'swift' => 'VICTIDJ1'],
    '567' => ['name' => 'PT. BANK HARDA INTERNATIONAL', 'swift' => 'HRDAIDJ1'],
    '945' => ['name' => 'PT. BANK AGRIS', 'swift' => 'AGSSIDJA'],
    '947' => ['name' => 'PT. BANK MAYBANK SYARIAH INDONESIA', 'swift' => 'MBBEIDJA'],
    '949' => ['name' => 'PT. BANK CTBC INDONESIA', 'swift' => 'CTCBIDJA'],
    '950' => ['name' => 'PT. BANK COMMONWEALTH', 'swift' => 'BICNIDJA'],
];
